site_name: Knowledgebase

theme: readthedocs
nav:
  - Overview:
    - index.md
  - 'Project Management':
    - iperka.md
  - 'Data Structures':
    - video_formats.md
    - color_models.md
  - Algorithms:
    - lossless_compression.md
plugins:
  - search
  - mermaid2
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
  - mdx_math
